name: Manual Test Dispatch

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:
    inputs:
      name:
        description: 'Name of the person to greet'
        required: true
        type: string
        default: 'Mona the Octocat'
      greeting:
        description: 'Type of greeting'
        required: true
        type: string
        default: 'How are you doing today?'
      test:
        description: 'Test to run'
        required: true
        default: 'unit'
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Greeting
        run: echo "Hello ${{ inputs.name }}! ${{ inputs.greeting }}"
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Run test
        run: npm run test